# Generated by Django 4.1.1 on 2022-10-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downlod_date', models.DateTimeField()),
                ('file_title', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=10)),
                ('file_url', models.URLField()),
            ],
        ),
    ]
