# Generated by Django 4.1.1 on 2022-10-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='DownloadHistory',
        ),
    ]
